Avoid reflection by adding type hints
remvee/ring-basic-authentication pull request #22
Opened 2021-11-07 19:43 UTC by joda

Makes it possible to use e.g. GraalVM

2021-11-08 15:56 UTC, remvee requested changes
Thanks!  Please address comments.

2021-11-08 15:56 UTC, remvee commented on src/ring/middleware/basic_authentication.clj
> +  (byte-transform #(.encode ^java.util.Base64$Encoder (Base64/getEncoder) ^bytes %) string))
Omitting `^java.util.Base64$Encoder` does not yield reflection warning.  Please remove when not needed.

2021-11-08 15:56 UTC, remvee commented on src/ring/middleware/basic_authentication.clj
> +  (byte-transform #(.decode ^java.util.Base64$Decoder (Base64/getDecoder) ^bytes %) string))
Same here.

2021-11-08 15:56 UTC, remvee commented on project.clj
> +  :global-vars {*warn-on-reflection* true})
Not a big fan of global-var, please use `(set! *warn-on-reflection* true)` in the namespace.

2021-11-11 11:25 UTC, remvee commented
Nevermind, I've cherry picked your commit and made the changes myself, see commit 0d20d01.

2021-11-11 11:25 UTC, closed without merging

2021-11-11 11:26 UTC, remvee commented
Oh, and pushed a new release (1.1.1).  Thanks for making this lib better!

2021-11-11 12:13 UTC, joda commented
Thanks @remvee, got occupied with other stuff

2021-11-11 12:29 UTC, remvee commented
No problem. I got impatient because some other issue popped up on this normally sleepy repo too. Thanks again.